 
@url = http://localhost:3007

### Get events

GET {{url}}/api/events

### Get menu
  
GET {{url}}/api/menu

### get event by id

GET {{url}}/api/events/6628531979030ef22fdd0cf7

### Add new menu item

POST {{url}}/api/menu
Content-Type: application/json

{
    "name": "Peach Cobbler",
    "description": "Try our delicious peach cobbler made with freshly picked peaches from the farmers market",
    "price": "$7.99"
}


### add new event
POST {{url}}/api/events
Content-Type: application/json

{
    "eventName": "FVTC open house",
    "eventDate": "10/21/25",
    "truckLocation": "1825 N. Bluemound Drive, Appleton, WI 54914",
    "hours":"12pm-3pm"
}

### Update menu item

PUT {{url}}/api/menu/662919947042626364552072
Content-Type: application/json

{
    "name": "Pulled Pork Sandwich with Slaw",
    "description": "New Description",
    "price": "$14.99"
}

### delete menu item

DELETE {{url}}/api/menu/6630335e102f877d4232a16b
